dj_bookmarks/bookmarks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^create/$', views.Create.as_view(), name='create'),
    url('^trash/$', views.Trash.as_view(), name='trash'),
    url('^search/$', views.Search.as_view(), name='search'),
    url('^update/(?P<pk>\d+)/$', views.Update.as_view(), name='update'),
    url('^delete/(?P<pk>\d+)/$', views.Delete.as_view(), name='delete'),
    url('^undelete/(?P<pk>\d+)/$', views.Undelete.as_view(), name='undelete'),
    url('^t:(?P<tag>[-\w]+)/$', views.List.as_view(), name='tag_search'),
    url('^$', views.List.as_view(), name='list'),
]

dj_bookmarks/dj_bookmarks/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from authentication.views import SignUpView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^accounts/', include('profiles.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^bookmarks/', include('bookmarks.urls.bookmarks', namespace='bookmarks')),
    url(r'^collections/', include('bookmarks.urls.collections', namespace='collections')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

dj_bookmarks/profiles/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^profile/$', views.ProfileView.as_view(), name='view'),
    url(r'^profile/edit/$', views.ProfileEditView.as_view(), name='edit'),
]

dj_bookmarks/templates/_partials/nav.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Bookmarks!</a>
        </div>
        <form action="{% url 'bookmarks:search' %}" class="navbar-left navbar-form">
            <div class="form-group">
                <input type="search" class="form-control" name="q" placeholder="Search" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
        </form>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li class="navbar-text">{{ user.profile.full_name }}</li>
                <li><a href="{% url 'bookmarks:list' %}">My Bookmarks</a></li>
                <li><a href="{% url 'collections:list' %}">My Collections</a></li>
                <li><a href="{% url 'bookmarks:trash' %}"><i class="glyphicon glyphicon-trash"></i></a></li>
                <li><a href="{% url 'bookmarks:create' %}"><i class="glyphicon glyphicon-plus"></i></a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>